// Generated by tools/fighter-gen.ts from the decomp (ftFox); do not edit by hand, run it again.
// ftFx_Submotion, struct ftFox_DatAttrs and ftFx_Init_MotionStateTable.
import type { Field } from '../attributes';
import type { MotionDef } from './index';

export const SUBMOTIONS: readonly string[] = ["SpecialNStart","SpecialNLoop","SpecialNEnd","SpecialAirNStart","SpecialAirNLoop","SpecialAirNEnd","SpecialSStart","SpecialS","SpecialSEnd","SpecialAirSStart","SpecialAirS","SpecialAirSEnd","SpecialHiHold","SpecialHiHoldAir","SpecialHi","SpecialHiLanding","SpecialHiFall","SpecialHiBound","SpecialLwStart","SpecialLwLoop","SpecialLwHit","SpecialLwEnd","SpecialAirLwStart","SpecialAirLwLoop","SpecialAirLwHit","SpecialAirLwEnd","AppealSStartR","AppealSStartL","AppealSR","AppealSL","AppealSEndR","AppealSEndL"];

export const SPECIAL_FIELDS: Field[] = [
  ['x0_FOX_BLASTER_UNK1', 0x0],
  ['x4_FOX_BLASTER_UNK2', 0x4],
  ['x8_FOX_BLASTER_UNK3', 0x8],
  ['xC_FOX_BLASTER_UNK4', 0xc],
  ['x10_FOX_BLASTER_ANGLE', 0x10],
  ['x14_FOX_BLASTER_VEL', 0x14],
  ['x18_FOX_BLASTER_LANDING_LAG', 0x18],
];

/** Own motion states: [motion id, state name, submotion (move) name, move id]. */
export const MOTIONS: MotionDef[] = [
  [341, 'SpecialNStart', 'SpecialNStart', 18],
  [342, 'SpecialNLoop', 'SpecialNLoop', 18],
  [343, 'SpecialNEnd', 'SpecialNEnd', 18],
  [344, 'SpecialAirNStart', 'SpecialAirNStart', 18],
  [345, 'SpecialAirNLoop', 'SpecialAirNLoop', 18],
  [346, 'SpecialAirNEnd', 'SpecialAirNEnd', 18],
  [347, 'SpecialSStart', 'SpecialSStart', 19],
  [348, 'SpecialS', 'SpecialS', 19],
  [349, 'SpecialSEnd', 'SpecialSEnd', 19],
  [350, 'SpecialAirSStart', 'SpecialAirSStart', 19],
  [351, 'SpecialAirS', 'SpecialAirS', 19],
  [352, 'SpecialAirSEnd', 'SpecialAirSEnd', 19],
  [353, 'SpecialHiHold', 'SpecialHiHold', 20],
  [354, 'SpecialHiHoldAir', 'SpecialHiHoldAir', 20],
  [355, 'SpecialHi', 'SpecialHi', 20],
  [356, 'SpecialAirHi', 'SpecialHi', 20],
  [357, 'SpecialHiLanding', 'SpecialHiLanding', 20],
  [358, 'SpecialHiFall', 'SpecialHiFall', 20],
  [359, 'SpecialHiBound', 'SpecialHiBound', 20],
  [360, 'SpecialLwStart', 'SpecialLwStart', 21],
  [361, 'SpecialLwLoop', 'SpecialLwLoop', 21],
  [362, 'SpecialLwHit', 'SpecialLwHit', 21],
  [363, 'SpecialLwEnd', 'SpecialLwEnd', 21],
  [364, 'SpecialLwTurn', 'SpecialLwLoop', 21],
  [365, 'SpecialAirLwStart', 'SpecialAirLwStart', 21],
  [366, 'SpecialAirLwLoop', 'SpecialAirLwLoop', 21],
  [367, 'SpecialAirLwHit', 'SpecialAirLwHit', 21],
  [368, 'SpecialAirLwEnd', 'SpecialAirLwEnd', 21],
  [369, 'SpecialAirLwTurn', 'SpecialAirLwLoop', 21],
  [370, 'AppealSStartR', 'AppealSStartR', 1],
  [371, 'AppealSStartL', 'AppealSStartL', 1],
  [372, 'AppealSR', 'AppealSR', 1],
  [373, 'AppealSL', 'AppealSL', 1],
  [374, 'AppealSEndR', 'AppealSEndR', 1],
  [375, 'AppealSEndL', 'AppealSEndL', 1],
];
