// Per-character facts from the decomp, generated by tools/fighter-gen.ts (one file per character).
/** An own motion state: [motion id, state name, submotion (move) name, move id (FtMoveId)]. */
export type MotionDef = [id: number, name: string, move: string, moveId: number];
